[[cddlib]]
arch = "aarch64"
git-tree-sha1 = "d404927e6c241215ee2871ba75c33e56548a63f0"
os = "macos"

    [[cddlib.download]]
    sha256 = "158c0221f043ae61870a5982bade69018beaeff6ce9392832f20a5b7b63141ea"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.aarch64-apple-darwin.tar.gz"
[[cddlib]]
arch = "aarch64"
git-tree-sha1 = "c8746256e74afc75439951454b80df699c403b7e"
libc = "glibc"
os = "linux"

    [[cddlib.download]]
    sha256 = "b67efcd002da7c26127ded174658f507562cdb181a34dbb7ae03e594a283380f"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.aarch64-linux-gnu.tar.gz"
[[cddlib]]
arch = "aarch64"
git-tree-sha1 = "e48573ddfed5e781ecbe424c98720f33d17fdfed"
libc = "musl"
os = "linux"

    [[cddlib.download]]
    sha256 = "94b5bed2cc10a6a97fa518c46cb50f2eac2cc0925f6fe6e2df3360b06ee9c4a1"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.aarch64-linux-musl.tar.gz"
[[cddlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f27afd6882e68b4c8558c162d0792a317de18ede"
libc = "glibc"
os = "linux"

    [[cddlib.download]]
    sha256 = "e6b4e5a1541496368eb7be844797268c1fbcd2f75b41cf3bad96cb675f37d9d2"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.armv6l-linux-gnueabihf.tar.gz"
[[cddlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f4eaa531eb0f29b72965c46f062e031740d1b195"
libc = "musl"
os = "linux"

    [[cddlib.download]]
    sha256 = "53bed7ff7d28bd6923afae261859b03ac797a27dc01425b4e1bcda95ea532338"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.armv6l-linux-musleabihf.tar.gz"
[[cddlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "531feff834affbd68705324e46aa26d696f9147e"
libc = "glibc"
os = "linux"

    [[cddlib.download]]
    sha256 = "02e157782c95b626288038021e716f701dcea621221e223cb13cd12bd2dd0fc3"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.armv7l-linux-gnueabihf.tar.gz"
[[cddlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2c0d91282b2206de2aafa549c019d43600bbb389"
libc = "musl"
os = "linux"

    [[cddlib.download]]
    sha256 = "9cb25be2717eda5901f9708024f4d6bc1a775e92183be3ca9c10e5eaeec9d25a"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.armv7l-linux-musleabihf.tar.gz"
[[cddlib]]
arch = "i686"
git-tree-sha1 = "7e81c7019adf85e845869c82d357c4365b0c7d4e"
libc = "glibc"
os = "linux"

    [[cddlib.download]]
    sha256 = "78ea05bde7bc7028644e86a539be070d456f1e8404f49d7875f9a83c558b97fd"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.i686-linux-gnu.tar.gz"
[[cddlib]]
arch = "i686"
git-tree-sha1 = "1862d3c080ac5a5fcd2130bf18e3b34e28e3814b"
libc = "musl"
os = "linux"

    [[cddlib.download]]
    sha256 = "46be2f996b167ac33c472f67f9fdd0b76c7fe23f188a0b6672e024093b865887"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.i686-linux-musl.tar.gz"
[[cddlib]]
arch = "i686"
git-tree-sha1 = "fb0310f4f71c4157c4b7a8d423ef727d7d7903ef"
os = "windows"

    [[cddlib.download]]
    sha256 = "5c172d14d942385b4b5e2aca4be7729fdfbd9ccbd74366ebb2587d5f21d16abc"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.i686-w64-mingw32.tar.gz"
[[cddlib]]
arch = "powerpc64le"
git-tree-sha1 = "1a6bf3685a80c81fe97c94349600e0a6f16d9de7"
libc = "glibc"
os = "linux"

    [[cddlib.download]]
    sha256 = "b23776d9fca116d08a625ff243c22f2ccf6421d85caf5ce1607a1eff31eb10cb"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.powerpc64le-linux-gnu.tar.gz"
[[cddlib]]
arch = "x86_64"
git-tree-sha1 = "39b5611c92d204556056ab0cf2d30984382f4a34"
os = "macos"

    [[cddlib.download]]
    sha256 = "22fba404ad581fde899050345abf0fb5809988d8152b7dcdf97a078549124ed3"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.x86_64-apple-darwin.tar.gz"
[[cddlib]]
arch = "x86_64"
git-tree-sha1 = "ec0212406c820d6b35b1c8b400a5ad8c67743fda"
libc = "glibc"
os = "linux"

    [[cddlib.download]]
    sha256 = "0e7cd08427d1529f9ac226cb65037512a71a7c706c8f0cab966288f7dd51b657"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.x86_64-linux-gnu.tar.gz"
[[cddlib]]
arch = "x86_64"
git-tree-sha1 = "dd590d8bde4d56aa29c0bb162e9fcce046ddc6b3"
libc = "musl"
os = "linux"

    [[cddlib.download]]
    sha256 = "14d96892f5895b6f5de21579aba368eacec40b8b9e1909bbfb49d52c5c8c9ab1"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.x86_64-linux-musl.tar.gz"
[[cddlib]]
arch = "x86_64"
git-tree-sha1 = "4ff795d3305bf978dd41d731aa13a2f99ead620b"
os = "freebsd"

    [[cddlib.download]]
    sha256 = "ed737ad3aceb2d91b4a90a5f479407972411d995328ecaca89f8e664a453c7e1"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.x86_64-unknown-freebsd.tar.gz"
[[cddlib]]
arch = "x86_64"
git-tree-sha1 = "30f6f81422a8ace8acae3454d6ed845e498d5573"
os = "windows"

    [[cddlib.download]]
    sha256 = "c74f632eba3cb5c132487d1ddad1a209737a771e425498b6868a5fd84f0c5be9"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.13+0/cddlib.v0.94.13.x86_64-w64-mingw32.tar.gz"
