[[cddlib]]
arch = "aarch64"
git-tree-sha1 = "1a642d440ef4c3df4be6fffeea1334ec4c877d60"
os = "macos"

    [[cddlib.download]]
    sha256 = "4ff11db6643e3b5215a8e4ebb75208143d4571b00ae5a7eb5966d4d095f26374"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.aarch64-apple-darwin.tar.gz"
[[cddlib]]
arch = "aarch64"
git-tree-sha1 = "32393e5b622893c7e43300de4dbc63dd1a95060a"
libc = "glibc"
os = "linux"

    [[cddlib.download]]
    sha256 = "d0bc43439f936693a34d6ca74053a7e4e3d5c565ce700620b5b3c068219306a7"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.aarch64-linux-gnu.tar.gz"
[[cddlib]]
arch = "aarch64"
git-tree-sha1 = "0cc028b824c720f3791332d9a8b6b0b2fcb27b0b"
libc = "musl"
os = "linux"

    [[cddlib.download]]
    sha256 = "c41827c67151d7be71aaf327bf88ab6dab296f4524650c5534572ae78bef5708"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.aarch64-linux-musl.tar.gz"
[[cddlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d3c057fe904289191a8cb107d413abb02ea8a0c6"
libc = "glibc"
os = "linux"

    [[cddlib.download]]
    sha256 = "fb1476069bdca29afa76c6e7b06252b78d5cb9a64ce125ca5a8483202bc6857f"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.armv6l-linux-gnueabihf.tar.gz"
[[cddlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bff4235450fa4ce89e39ab9b2b665c17fd53276c"
libc = "musl"
os = "linux"

    [[cddlib.download]]
    sha256 = "658a60027c73c4590f89fbcd068b525bc802a0139e34617ee71975391d5126f3"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.armv6l-linux-musleabihf.tar.gz"
[[cddlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "44ed9178dc9d59b1584c5d7f6180a06d89392e58"
libc = "glibc"
os = "linux"

    [[cddlib.download]]
    sha256 = "d185a95ca43af0d7d203ca34d4f68854a04c1495ff222b2b5e130a5f34aa8e66"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.armv7l-linux-gnueabihf.tar.gz"
[[cddlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40523c0f75f1f4120de4a4896e0cbfbdfa22168a"
libc = "musl"
os = "linux"

    [[cddlib.download]]
    sha256 = "c0b3e9b2ebc1bc2c30188399a3c7be4b8450eb849befb610630d865ecec4b522"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.armv7l-linux-musleabihf.tar.gz"
[[cddlib]]
arch = "i686"
git-tree-sha1 = "bdd4545331b1f553bdd34295158dc27ae0ea3e98"
libc = "glibc"
os = "linux"

    [[cddlib.download]]
    sha256 = "0d51ecc0b9aea5e4b276d450e36c473c757585b3ae48e758df0965f5ee6c9d3c"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.i686-linux-gnu.tar.gz"
[[cddlib]]
arch = "i686"
git-tree-sha1 = "7bc7ffae1b819252b628543744efa9a132cbd9c1"
libc = "musl"
os = "linux"

    [[cddlib.download]]
    sha256 = "4df3c12218c2aaa8476ce3defcca51856c1836ed49cdda311e29b0d46f5f7f8e"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.i686-linux-musl.tar.gz"
[[cddlib]]
arch = "i686"
git-tree-sha1 = "e23c801e5a9a1b3f394e96d272863523726be018"
os = "windows"

    [[cddlib.download]]
    sha256 = "49f863c2dc897c748682adaab5cd0671cf89592ee733a4fe94ce5ba134e5bbd2"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.i686-w64-mingw32.tar.gz"
[[cddlib]]
arch = "powerpc64le"
git-tree-sha1 = "b60011a682561917c3656bcffeb87f2dcad34bf8"
libc = "glibc"
os = "linux"

    [[cddlib.download]]
    sha256 = "3b83a9effb1b9007f7eea2eaa7045992ddee866c3507fc4e0aa46966f8a83b02"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.powerpc64le-linux-gnu.tar.gz"
[[cddlib]]
arch = "x86_64"
git-tree-sha1 = "0e1ba657b92ef05d4f578c4ccb7bde5ab4359277"
os = "macos"

    [[cddlib.download]]
    sha256 = "208cf862176037c0ad80c0352c31b7960579cacd2c350e437b70f0750fb9d9f4"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.x86_64-apple-darwin.tar.gz"
[[cddlib]]
arch = "x86_64"
git-tree-sha1 = "2c602b7b18fbeff1c121a7533547fd7f518d4d7e"
libc = "glibc"
os = "linux"

    [[cddlib.download]]
    sha256 = "56567517fdee07178ae7276fcf2d77ee4601bb2376ccd8bef832052579e8b63a"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.x86_64-linux-gnu.tar.gz"
[[cddlib]]
arch = "x86_64"
git-tree-sha1 = "e1b57e662535bad847e17a4ce598644af12f471d"
libc = "musl"
os = "linux"

    [[cddlib.download]]
    sha256 = "5d70901f39200068c3a879723c076c600b0e5240ef9bcacd06de3de63a91f785"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.x86_64-linux-musl.tar.gz"
[[cddlib]]
arch = "x86_64"
git-tree-sha1 = "823c6b1f50830abcaac5d1e5dc94dae2c631553f"
os = "freebsd"

    [[cddlib.download]]
    sha256 = "c64a1cf3b645206d5e9669f3e018a051ae61215cd7cdbf96c685795f52e1f3e2"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.x86_64-unknown-freebsd.tar.gz"
[[cddlib]]
arch = "x86_64"
git-tree-sha1 = "f9ad68af11279d77ccf39d871c43a628d4218e49"
os = "windows"

    [[cddlib.download]]
    sha256 = "af3b22fde6a71eac0883ba1f069d39b0a7f846a45fc9b3f67f417f9371455b0c"
    url = "https://github.com/JuliaBinaryWrappers/cddlib_jll.jl/releases/download/cddlib-v0.94.14+0/cddlib.v0.94.14.x86_64-w64-mingw32.tar.gz"
