# Autogenerated wrapper script for cddlib_jll for armv6l-linux-gnueabihf
export libcdd, libcddgmp

using GMP_jll
JLLWrappers.@generate_wrapper_header("cddlib")
JLLWrappers.@declare_library_product(libcdd, "libcdd.so.0")
JLLWrappers.@declare_library_product(libcddgmp, "libcddgmp.so.0")
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_library_product(
        libcdd,
        "lib/libcdd.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcddgmp,
        "lib/libcddgmp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
