# Autogenerated wrapper script for cddlib_jll for x86_64-apple-darwin
export libcdd, libcddgmp

using GMP_jll
JLLWrappers.@generate_wrapper_header("cddlib")
JLLWrappers.@declare_library_product(libcdd, "@rpath/libcdd.0.dylib")
JLLWrappers.@declare_library_product(libcddgmp, "@rpath/libcddgmp.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_library_product(
        libcdd,
        "lib/libcdd.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcddgmp,
        "lib/libcddgmp.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
